
# Forum Post descriptor (Forum lib)

parent: publications

fields:
    message:    string
    forum_id:   ref
    parent_id:  ref=0


indexes:
     - INDEX(user_id)
     - FULLTEXT(message)
     