
# Forum descriptor (Forum lib)

parent: publications

fields:
    description:  string
    position:     integer
    parent_id:    ref=0


indexes:
     - INDEX(user_id)
     - INDEX(parent_id)
     - FULLTEXT(description)
     