
# Forum Post descriptor (Forum lib)

parent: publications

fields:
    message:    string
    forum_id:   ref
    parent_id:  ref=0
    post_date:  datetime[nullable]    # Last date a post of the forum was edited/added


indexes:
     - INDEX(user_id)
     - FULLTEXT(message)
     