
# Roles: visitor, member, moderator, administrator, developer

http:
    home:
        path: "/"
        controller: "HomeController"
        
    user_login:
        path: "/user_login.html"
        controller: "UserLoginController"
        
    sample_twig:
        path: "/sample_twig.html"
        controller: "TwigSampleController"
        
    thread:
        path: "/thread.html"
        controller: "ThreadController"
        
    faq:
        path: "/faq.html"
        render: "app/faq"
        
    adm_mysettings:
        path: "/admin/mes_parametres.html"
        controller: "AdminMySettingsController"
        restrictTo:
          role: administrator
        
    adm_users:
        path: "/admin/users.html"
        controller: "AdminUserListController"
        restrictTo:
          role: administrator
        
    adm_user:
        path: "/admin/user/{id:userID}.html"
        controller: "AdminUserEditController"
        restrictTo:
          role: administrator
        
    dev_entities:
        path: "/admin/dev_entities.html"
        controller: "DevEntitiesController"
        restrictTo:
          role: developer
        
    file_download:
        path: "/download/{id:fileID}"
        controller: "FileDownloadController"
        
#    home:
#        path: "/path/in/array/config"
#        method: "POST|GET"
#        method: "GET"
#        controller: "HomeController"
#    home2: "/path/with/all/methods->HomeController"
#    home3: "POST(/path/for/POST/method)->HomeController"
    
